# Project: sample project
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Final.o
LINKOBJ  = Final.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -L"C:/Users/Lenovo/Downloads/SDL2-2.26.5/x86_64-w64-mingw32/lib" -L"C:/Users/Lenovo/Downloads/SDL2_image-2.6.3/x86_64-w64-mingw32/lib" -L"C:/Users/Lenovo/Downloads/SDL2_ttf-devel-2.20.2-mingw/SDL2_ttf-2.20.2/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/Users/Lenovo/Downloads/SDL2-2.26.5/x86_64-w64-mingw32/lib" -lmingw32 -lSDL2main -lSDL2 -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/Lenovo/Downloads/SDL2_image-2.6.3/x86_64-w64-mingw32/include" -I"C:/Users/Lenovo/Downloads/SDL2-2.26.5/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/Lenovo/Downloads/SDL2_image-2.6.3/x86_64-w64-mingw32/include/SDL2"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"C:/Users/Lenovo/Downloads/SDL2-2.26.5/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/Lenovo/Downloads/SDL2_image-2.6.3/x86_64-w64-mingw32/include/SDL2" -I"C:/Users/Lenovo/Downloads/SDL2-2.26.5/x86_64-w64-mingw32/include" -I"C:/Users/Lenovo/Downloads/SDL2_ttf-devel-2.20.2-mingw/SDL2_ttf-2.20.2/x86_64-w64-mingw32/include"
BIN      = "sample project.exe"
CXXFLAGS = $(CXXINCS) -lmingw32 -lSDL2 -lSDL2_tff
CFLAGS   = $(INCS) -lmingw32 -lSDL2 -lSDL2_tff
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Final.o: Final.cpp
	$(CPP) -c Final.cpp -o Final.o $(CXXFLAGS)
